# Generated by Django 3.2.18 on 2023-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='PhoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
